import type { OpeningArchetype } from "./opening-archetype.types";

export const OPENING_ARCHETYPES: OpeningArchetype[] = [
  {
    key: "in_medias_res",
    displayName: "In Medias Res",
    promptShape:
      "{{pc.name}} sente {{sensory.anchor}} antes de qualquer pensamento. {{imminent_threat}} está a um passo. Não há tempo para escolher como respirar, só para agir.",
    requiredSlots: ["pc.name", "sensory.anchor", "imminent_threat"],
    optionalSlots: ["npc.bystander.name", "location.name"],
    bannedPhrases: ["era uma vez", "de repente", "fazia muito tempo"],
    requiredVoiceProfiles: ["heroic-high-fantasy", "grim-low-fantasy", "comico-pulp"],
    compatiblePcTags: ["fighter", "barbarian", "rogue", "high-dex", "martial"],
    incompatiblePcTags: [],
    emotionalArc: "rise",
    weightDefault: 1.5,
    fewShotExample:
      "Goma sente o gosto metálico do sangue antes de ouvir o grito. Uma flecha treme na madeira ao lado do rosto. O arqueiro recarregou.",
    isActive: true,
    since: "037",
    opensInDialogue: false,
    initialFocalNpcSlot: null,
  },
  {
    key: "misterio_camara_vazia",
    displayName: "Mistério da Câmara Vazia",
    promptShape:
      "{{location.name}} deveria estar habitado. {{pc.name}} entra e encontra {{anomaly.detail}}. O silêncio aqui não é vazio; está esperando.",
    requiredSlots: ["pc.name", "anomaly.detail", "location.name"],
    optionalSlots: ["npc.witness.name", "missing_object"],
    bannedPhrases: ["misteriosamente", "estranhamente", "como num sonho"],
    requiredVoiceProfiles: ["investigativo-misterioso", "grim-low-fantasy"],
    compatiblePcTags: [
      "wizard",
      "cleric",
      "scholar",
      "perception-trained",
      "background:investigator",
      "caster",
    ],
    incompatiblePcTags: ["chaotic-stupid"],
    emotionalArc: "man-in-hole",
    weightDefault: 1,
    fewShotExample:
      "A Câmara de Projetos deveria fumar com vinte mãos no trabalho. Maguin entra: roldanas giram sozinhas, planos rasgados batem no chão. Uma cadeira ainda quente.",
    isActive: true,
    since: "037",
    opensInDialogue: false,
    initialFocalNpcSlot: null,
  },
  {
    key: "perda_irrecuperavel",
    displayName: "Perda Irrecuperável",
    promptShape:
      "{{pc.name}} percebe primeiro a ausência: {{missing_object}} não está onde deveria. {{sensory.anchor}} prende a garganta. Alguém levou mais do que um objeto.",
    requiredSlots: ["pc.name", "missing_object", "sensory.anchor"],
    optionalSlots: ["location.name", "npc.witness.name"],
    bannedPhrases: ["algo estava errado", "um vazio no peito"],
    requiredVoiceProfiles: [
      "heroic-high-fantasy",
      "grim-low-fantasy",
      "investigativo-misterioso",
    ],
    compatiblePcTags: ["bond:mentor", "bond:lost-love", "flaw:obsession", "ideal:redemption"],
    incompatiblePcTags: [],
    emotionalArc: "fall",
    weightDefault: 1,
    fewShotExample:
      "O cofre ainda está fechado. A chave de cobre, não. No veludo, só a marca limpa onde ela repousou por anos.",
    isActive: true,
    since: "037",
    opensInDialogue: false,
    initialFocalNpcSlot: null,
  },
  {
    key: "encontro_fatidico",
    displayName: "Encontro Fatídico",
    promptShape:
      "{{pc.name}} cruza o olhar de {{npc.stranger.name}} antes de qualquer palavra. {{npc.stranger.first_glance}}. Entre vocês, {{stake_object}} — e a certeza incômoda de que ele veio por isso.",
    requiredSlots: ["pc.name", "npc.stranger.name", "npc.stranger.first_glance", "stake_object"],
    optionalSlots: ["weather", "location.name"],
    bannedPhrases: ["o destino quis", "como por acaso", "na poeira do tempo"],
    requiredVoiceProfiles: ["heroic-high-fantasy", "investigativo-misterioso"],
    compatiblePcTags: ["bard", "warlock", "high-charisma", "bond:mentor", "ideal:redemption"],
    incompatiblePcTags: [],
    emotionalArc: "cinderella",
    weightDefault: 1,
    fewShotExample:
      "Maguin cruza o olhar do velho antes de qualquer palavra. Óleo preto nas mãos, nenhum sorriso. Entre vocês, um plano rasgado pregado na parede.",
    isActive: true,
    since: "037",
    opensInDialogue: true,
    initialFocalNpcSlot: "npc.encounter.focal",
  },
  {
    key: "retorno_inesperado",
    displayName: "Retorno Inesperado",
    promptShape:
      "{{location.name}} mudou desde a última lembrança de {{pc.name}}. {{sensory.anchor}} denuncia uma presença antiga. Algo que devia ficar enterrado aprendeu o caminho de volta.",
    requiredSlots: ["pc.name", "location.name", "sensory.anchor"],
    optionalSlots: ["npc.witness.name", "anomaly.detail"],
    bannedPhrases: ["muito tempo atrás", "memórias voltam"],
    requiredVoiceProfiles: [],
    compatiblePcTags: ["bond:mentor", "background:soldier", "ideal:redemption"],
    incompatiblePcTags: [],
    emotionalArc: "return",
    weightDefault: 0.9,
    fewShotExample:
      "A torre da infância não está em ruínas. Está acesa. E alguém lá dentro usa a mesma canção que seu mestre assobiava.",
    isActive: true,
    since: "037",
    opensInDialogue: false,
    initialFocalNpcSlot: null,
  },
  {
    key: "descoberta_proibida",
    displayName: "Descoberta Proibida",
    promptShape:
      "{{pc.name}} encontra {{anomaly.detail}} escondido sob {{stake_object}}. {{sensory.anchor}} atravessa o ar. O segredo não pede licença; pede preço.",
    requiredSlots: ["pc.name", "anomaly.detail", "stake_object", "sensory.anchor"],
    optionalSlots: ["location.name"],
    bannedPhrases: ["segredo ancestral", "conhecimento proibido"],
    requiredVoiceProfiles: ["heroic-high-fantasy", "grim-low-fantasy", "investigativo-misterioso"],
    compatiblePcTags: ["wizard", "warlock", "caster", "scholar", "flaw:obsession"],
    incompatiblePcTags: [],
    emotionalArc: "icarus",
    weightDefault: 1,
    fewShotExample:
      "Sob a tampa do relicário há um mapa que se desenha sozinho. A tinta segue o pulso de Maguin.",
    isActive: true,
    since: "037",
    opensInDialogue: false,
    initialFocalNpcSlot: null,
  },
  {
    key: "divida_cobrada",
    displayName: "Dívida Cobrada",
    promptShape:
      "{{npc.stranger.name}} sabe o nome de {{pc.name}}. {{npc.stranger.first_glance}}. Sobre {{stake_object}}, a cobrança chega simples: pague agora ou escolha quem sangra depois.",
    requiredSlots: ["pc.name", "npc.stranger.name", "npc.stranger.first_glance", "stake_object"],
    optionalSlots: ["location.name"],
    bannedPhrases: ["dívida antiga", "preço do passado"],
    requiredVoiceProfiles: ["grim-low-fantasy", "comico-pulp"],
    compatiblePcTags: ["rogue", "warlock", "background:criminal", "flaw:greed", "bond:mentor"],
    incompatiblePcTags: [],
    emotionalArc: "man-in-hole",
    weightDefault: 0.95,
    fewShotExample:
      "A mulher conhece seu nome e o valor exato da sua bolsa. O contrato na mesa tem sua assinatura, mas você nunca o viu.",
    isActive: true,
    since: "037",
    opensInDialogue: true,
    initialFocalNpcSlot: "npc.encounter.focal",
  },
  {
    key: "perseguicao_imediata",
    displayName: "Perseguição Imediata",
    promptShape:
      "{{pc.name}} ouve {{imminent_threat}} atrás de si. {{location.name}} vira corredor estreito, gente demais, saídas de menos. {{sensory.anchor}} marca cada segundo perdido.",
    requiredSlots: ["pc.name", "imminent_threat", "location.name", "sensory.anchor"],
    optionalSlots: ["weather", "npc.stranger.name"],
    bannedPhrases: ["sem olhar para trás", "correndo contra o tempo"],
    requiredVoiceProfiles: ["heroic-high-fantasy", "grim-low-fantasy", "comico-pulp"],
    compatiblePcTags: ["rogue", "monk", "ranger", "high-dex", "martial"],
    incompatiblePcTags: [],
    emotionalArc: "rise",
    weightDefault: 1.05,
    fewShotExample:
      "O apito corta a feira. Três botas pesadas viram a esquina. A viela à direita acabou de ser fechada por uma carroça.",
    isActive: true,
    since: "037",
    opensInDialogue: false,
    initialFocalNpcSlot: null,
  },
];
