export const ErrorCode = {
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_PERMISSION_DENIED: "AUTH_PERMISSION_DENIED",

  AGENT_UPSTREAM_ERROR: "AGENT_UPSTREAM_ERROR",
  AGENT_TIMEOUT: "AGENT_TIMEOUT",
  AGENT_UNREACHABLE: "AGENT_UNREACHABLE",
  AGENT_SESSION_NOT_FOUND: "AGENT_SESSION_NOT_FOUND",
  AGENT_INVALID_RESPONSE: "AGENT_INVALID_RESPONSE",

  CAMPAIGN_NOT_FOUND: "CAMPAIGN_NOT_FOUND",
  CAMPAIGN_PLAYER_LIMIT_REACHED: "CAMPAIGN_PLAYER_LIMIT_REACHED",
  CAMPAIGN_FORBIDDEN: "CAMPAIGN_FORBIDDEN",

  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_NOT_JOINABLE: "SESSION_NOT_JOINABLE",
  SESSION_DIALOGUE_NOT_ACTIVE: "SESSION_DIALOGUE_NOT_ACTIVE",
  SESSION_SOCIAL_COLLECTIVE_REQUIRED: "SESSION_SOCIAL_COLLECTIVE_REQUIRED",
  SESSION_BIMODAL_LOOP_DISABLED: "SESSION_BIMODAL_LOOP_DISABLED",
  NARRATIVE_TURN_NOT_ALLOWED_IN_IDLE_OPEN:
    "NARRATIVE_TURN_NOT_ALLOWED_IN_IDLE_OPEN",
  NARRATIVE_TURN_SYSTEM_HINT_DEPRECATED:
    "NARRATIVE_TURN_SYSTEM_HINT_DEPRECATED",
  NARRATIVE_TURN_SYSTEM_HINT_LEGACY_ALIAS:
    "NARRATIVE_TURN_SYSTEM_HINT_LEGACY_ALIAS",
  NARRATIVE_TRANSITION_SCOPE_INVALID:
    "NARRATIVE_TRANSITION_SCOPE_INVALID",

  COMBAT_NOT_FOUND: "COMBAT_NOT_FOUND",
  COMBAT_TURN_INVALID: "COMBAT_TURN_INVALID",
  COMBAT_PARTICIPANT_NOT_FOUND: "COMBAT_PARTICIPANT_NOT_FOUND",

  CHARACTER_NOT_FOUND: "CHARACTER_NOT_FOUND",
  CHARACTER_FORBIDDEN: "CHARACTER_FORBIDDEN",

  SPELL_SLOT_UNAVAILABLE: "SPELL_SLOT_UNAVAILABLE",
  SPELL_NOT_PREPARED: "SPELL_NOT_PREPARED",

  VALIDATION_INVALID_PAYLOAD: "VALIDATION_INVALID_PAYLOAD",
  VALIDATION_MISSING_FIELD: "VALIDATION_MISSING_FIELD",

  SYSTEM_INTERNAL_ERROR: "SYSTEM_INTERNAL_ERROR",
  SYSTEM_UNAVAILABLE: "SYSTEM_UNAVAILABLE",
  SYSTEM_RATE_LIMITED: "SYSTEM_RATE_LIMITED",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",

  EVENT_TYPE_NOT_REGISTERED: "EVENT_TYPE_NOT_REGISTERED",
  TRACE_ID_INVALID: "TRACE_ID_INVALID",

  WEATHER_INVALID_BIOME: "WEATHER_INVALID_BIOME",
  CLOCK_NEGATIVE_HOURS: "CLOCK_NEGATIVE_HOURS",
  CHAOS_OUT_OF_RANGE: "CHAOS_OUT_OF_RANGE",
  SPELL_BLOCKED_DEAD_MAGIC: "SPELL_BLOCKED_DEAD_MAGIC",

  ENCOUNTER_CREATE_FAILED: "ENCOUNTER_CREATE_FAILED",
  ENCOUNTER_NO_TARGETS_IN_SCENE: "ENCOUNTER_NO_TARGETS_IN_SCENE",
  REVIVIFY_INELIGIBLE: "REVIVIFY_INELIGIBLE",
  REVIVIFY_TARGET_NOT_DEAD: "REVIVIFY_TARGET_NOT_DEAD",
  REVIVIFY_BODY_DESTROYED: "REVIVIFY_BODY_DESTROYED",
  CONDITION_INVALID_SLUG: "CONDITION_INVALID_SLUG",
  CONDITION_TARGET_NOT_FOUND: "CONDITION_TARGET_NOT_FOUND",
  CONDITION_DURATION_INVALID: "CONDITION_DURATION_INVALID",
  EXHAUSTION_LEVELS_REQUIRED: "EXHAUSTION_LEVELS_REQUIRED",
  CONDITION_BLOCKED_BY_IMMUNITY: "CONDITION_BLOCKED_BY_IMMUNITY",
  INVENTORY_ITEM_NOT_FOUND: "INVENTORY_ITEM_NOT_FOUND",
  ITEM_OWNERSHIP_MISMATCH: "ITEM_OWNERSHIP_MISMATCH",
  CURRENCY_NEGATIVE_FORBIDDEN: "CURRENCY_NEGATIVE_FORBIDDEN",
  CURRENCY_DELTA_EMPTY: "CURRENCY_DELTA_EMPTY",
  NPC_NOT_FOUND: "NPC_NOT_FOUND",
  NPC_FOCAL_NOT_IN_SCENE: "NPC_FOCAL_NOT_IN_SCENE",
  NPC_LOCATION_MISMATCH: "NPC_LOCATION_MISMATCH",
  NPC_DUPLICATE_NAME: "NPC_DUPLICATE_NAME",
  NPC_ROUTINE_INVALID_SLOT: "NPC_ROUTINE_INVALID_SLOT",
  ROLE_HINT_INVALID: "ROLE_HINT_INVALID",
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  SCENE_NOT_FOUND: "SCENE_NOT_FOUND",
  NPC_NOT_HOSTILE_CAPABLE: "NPC_NOT_HOSTILE_CAPABLE",
  PARTICIPANT_PLACEMENT_FAILED: "PARTICIPANT_PLACEMENT_FAILED",
  LOOT_TABLE_NOT_FOUND: "LOOT_TABLE_NOT_FOUND",
  LOOT_ALREADY_ROLLED: "LOOT_ALREADY_ROLLED",
  LOOT_PARAMS_INVALID: "LOOT_PARAMS_INVALID",
  MONSTER_HAS_NO_LOOT: "MONSTER_HAS_NO_LOOT",
  MONSTER_NOT_FOUND: "MONSTER_NOT_FOUND",
  RANDOM_ENCOUNTER_POOL_EMPTY: "RANDOM_ENCOUNTER_POOL_EMPTY",
  RANDOM_ENCOUNTER_INVALID_LOCATION: "RANDOM_ENCOUNTER_INVALID_LOCATION",
  PARTICIPANT_NOT_FOUND: "PARTICIPANT_NOT_FOUND",
  DYING_STATE_TRANSITION_INVALID: "DYING_STATE_TRANSITION_INVALID",
  DYING_STATE_REQUIRES_HP_RESTORE: "DYING_STATE_REQUIRES_HP_RESTORE",

  SUMMARIZE_LLM_TIMEOUT: "SUMMARIZE_LLM_TIMEOUT",
  SUMMARIZE_LLM_FAILURE: "SUMMARIZE_LLM_FAILURE",
  SUMMARIZE_INVALID_INPUT: "SUMMARIZE_INVALID_INPUT",
  SUMMARIZE_AUTH_FAILED: "SUMMARIZE_AUTH_FAILED",
  SESSION_LAST_MESSAGE_MISMATCH: "SESSION_LAST_MESSAGE_MISMATCH",

  IDEMPOTENCY_CACHE_MISS_AFTER_RACE: "IDEMPOTENCY_CACHE_MISS_AFTER_RACE",

  NARRATIVE_DECISION_AFFECTED_ENTITY_NOT_FOUND:
    "NARRATIVE_DECISION_AFFECTED_ENTITY_NOT_FOUND",

  CAMPAIGN_SLUG_NOT_RESOLVED: "CAMPAIGN_SLUG_NOT_RESOLVED",

  LEGACY_ENDPOINT_DEPRECATED: "LEGACY_ENDPOINT_DEPRECATED",

  LOCATION_CONNECTION_BLOCKED: "LOCATION_CONNECTION_BLOCKED",
  LOCATION_REQUIREMENTS_NOT_MET: "LOCATION_REQUIREMENTS_NOT_MET",
  PHASE_GATE_PENDING_CONFIRMATION: "PHASE_GATE_PENDING_CONFIRMATION",
  COLD_OPEN_NO_ARCHETYPE_MATCH: "COLD_OPEN_NO_ARCHETYPE_MATCH",
  COLD_OPEN_SLOT_RESOLUTION_FAILED: "COLD_OPEN_SLOT_RESOLUTION_FAILED",
  COLD_OPEN_GENERATION_TIMEOUT: "COLD_OPEN_GENERATION_TIMEOUT",
  META_QUERY_RATE_LIMIT_EXCEEDED: "META_QUERY_RATE_LIMIT_EXCEEDED",
  META_QUERY_KNOWLEDGE_SCOPE_VIOLATION:
    "META_QUERY_KNOWLEDGE_SCOPE_VIOLATION",
  NARRATIVE_REACHABLE_LOCATIONS_SESSION_NOT_FOUND:
    "NARRATIVE_REACHABLE_LOCATIONS_SESSION_NOT_FOUND",
  NARRATIVE_REACHABLE_LOCATIONS_NO_ACTIVE_SCENE:
    "NARRATIVE_REACHABLE_LOCATIONS_NO_ACTIVE_SCENE",
  SCENE_POI_OBSERVATION_GEN_FAILED: "SCENE_POI_OBSERVATION_GEN_FAILED",
  SCENE_POI_OBSERVATION_NOT_FOUND: "SCENE_POI_OBSERVATION_NOT_FOUND",
  SCENE_POI_OBSERVATION_INVALID_POI: "SCENE_POI_OBSERVATION_INVALID_POI",
  DIALOGUE_SKILL_ROLL_CAP_EXCEEDED: "DIALOGUE_SKILL_ROLL_CAP_EXCEEDED",
  DIALOGUE_REVEAL_FAILED: "DIALOGUE_REVEAL_FAILED",
  DIALOGUE_REVEAL_NOT_AVAILABLE: "DIALOGUE_REVEAL_NOT_AVAILABLE",
  TRAVEL_ACTION_NO_ACTIVE_TRAVEL: "TRAVEL_ACTION_NO_ACTIVE_TRAVEL",
  TRAVEL_ACTION_INVALID_KIND: "TRAVEL_ACTION_INVALID_KIND",
  TRAVEL_ACTION_RATIONS_REQUIRED: "TRAVEL_ACTION_RATIONS_REQUIRED",
  TRAVEL_ACTION_INSUFFICIENT_RATIONS: "TRAVEL_ACTION_INSUFFICIENT_RATIONS",
  TRAVEL_ACTION_EXHAUSTION_CAP: "TRAVEL_ACTION_EXHAUSTION_CAP",
  TRAVEL_ACTION_UNSAFE_LONG_REST: "TRAVEL_ACTION_UNSAFE_LONG_REST",
  TRAVEL_ACTION_ROUTE_INVALID: "TRAVEL_ACTION_ROUTE_INVALID",
  TRAVEL_ACTION_INVALID_REROUTE: "TRAVEL_ACTION_INVALID_REROUTE",
  TRAVEL_ACTION_DISABLED_BY_FLAG: "TRAVEL_ACTION_DISABLED_BY_FLAG",
  TRAVEL_ACTION_GUARD_FAILED: "TRAVEL_ACTION_GUARD_FAILED",
  NARRATIVE_TURN_IN_PROGRESS: "NARRATIVE_TURN_IN_PROGRESS",

  BOOKEND_NPC_REFERENCE_VIOLATION: "BOOKEND_NPC_REFERENCE_VIOLATION",
  BOOKEND_PLANNER_TIMEOUT: "BOOKEND_PLANNER_TIMEOUT",
  BOOKEND_WRITER_TIMEOUT: "BOOKEND_WRITER_TIMEOUT",
  BOOKEND_ARTIFACT_NOT_FOUND: "BOOKEND_ARTIFACT_NOT_FOUND",
  BOOKEND_DECISION_INCONSISTENT: "BOOKEND_DECISION_INCONSISTENT",
  CLOSING_SEED_COMMIT_FAILED: "CLOSING_SEED_COMMIT_FAILED",
  CLOSING_SEED_LEAKAGE_DETECTED: "CLOSING_SEED_LEAKAGE_DETECTED",
  OUTCOME_TIER_DERIVATION_INVALID: "OUTCOME_TIER_DERIVATION_INVALID",
  DIEGETIC_RITUAL_NOT_FOUND: "DIEGETIC_RITUAL_NOT_FOUND",
  TWO_BEAT_STRUCTURE_VIOLATION: "TWO_BEAT_STRUCTURE_VIOLATION",
  IDENTITY_TAGS_LIMIT_EXCEEDED: "IDENTITY_TAGS_LIMIT_EXCEEDED",
  CHRONICLE_TIER_INVALID_TRANSITION: "CHRONICLE_TIER_INVALID_TRANSITION",
  DOWNTIME_TURNS_OUT_OF_RANGE: "DOWNTIME_TURNS_OUT_OF_RANGE",
  NL_TRIGGER_AUDITOR_INCONCLUSIVE: "NL_TRIGGER_AUDITOR_INCONCLUSIVE",
  CHAOS_FACTOR_CLAMP_VIOLATION: "CHAOS_FACTOR_CLAMP_VIOLATION",

  ADMIN_METRICS_PERIOD_INVALID: "ADMIN_METRICS_PERIOD_INVALID",
  ADMIN_METRICS_FILTER_INVALID: "ADMIN_METRICS_FILTER_INVALID",
  ADMIN_METRICS_USER_NOT_FOUND: "ADMIN_METRICS_USER_NOT_FOUND",
  ADMIN_METRICS_EXPORT_LIMIT_EXCEEDED: "ADMIN_METRICS_EXPORT_LIMIT_EXCEEDED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ALL_ERROR_CODES: readonly ErrorCode[] = Object.values(
  ErrorCode,
) as readonly ErrorCode[];

export function assertNever(x: never, msg = "Unhandled discriminant"): never {
  throw new Error(`${msg}: ${JSON.stringify(x)}`);
}

export function isErrorCode(value: unknown): value is ErrorCode {
  return (
    typeof value === "string" && ALL_ERROR_CODES.includes(value as ErrorCode)
  );
}