export enum Entities {
  AbilityScore = 'AbilityScoreEntity',
  Alignment = 'AlignmentEntity',
  Background = 'BackgroundEntity',
  Class = 'ClassEntity',
  Condition = 'ConditionEntity',
  DamageType = 'DamageTypeEntity',
  Equipment = 'EquipmentEntity',
  EquipmentCategory = 'EquipmentCategoryEntity',
  Feat = 'FeatEntity',
  Feature = 'FeatureEntity',
  Language = 'LanguageEntity',
  Level = 'LevelEntity',
  MagicItem = 'MagicItemEntity',
  MagicSchool = 'MagicSchoolEntity',
  Monster = 'MonsterEntity',
  Proficiency = 'ProficiencyEntity',
  Race = 'RaceEntity',
  Rule = 'RuleEntity',
  RuleSection = 'RuleSectionEntity',
  Shared = 'SharedEntity',
  Skill = 'SkillEntity',
  Spell = 'SpellEntity',
  Subclass = 'SubclassEntity',
  Subrace = 'SubraceEntity',
  Trait = 'TraitEntity',
  WeaponMasteryProperty = 'WeaponMasteryPropertyEntity',
  WeaponProperty = 'WeaponPropertyEntity',
}

export const entityDictionary = {
  [Entities.AbilityScore]: 'ability_scores',
  [Entities.Alignment]: 'alignments',
  [Entities.Background]: 'backgrounds',
  [Entities.Class]: 'classes',
  [Entities.Condition]: 'conditions',
  [Entities.DamageType]: 'damage_types',
  [Entities.Equipment]: 'equipment',
  [Entities.EquipmentCategory]: 'equipment_categories',
  [Entities.Feat]: 'feats',
  [Entities.Feature]: 'features',
  [Entities.Language]: 'languages',
  [Entities.Level]: 'levels',
  [Entities.MagicItem]: 'magic_items',
  [Entities.MagicSchool]: 'magic_schools',
  [Entities.Monster]: 'monsters',
  [Entities.Proficiency]: 'proficiencies',
  [Entities.Race]: 'races',
  [Entities.Rule]: 'rules',
  [Entities.RuleSection]: 'rule_sections',
  [Entities.Shared]: 'shared',
  [Entities.Skill]: 'skills',
  [Entities.Spell]: 'spells',
  [Entities.Subclass]: 'subclasses',
  [Entities.Subrace]: 'subraces',
  [Entities.Trait]: 'traits',
  [Entities.WeaponMasteryProperty]: 'weapon_mastery_properties',
  [Entities.WeaponProperty]: 'weapon_properties',
};
