import { MigrationInterface, QueryRunner } from "typeorm";

export class MigrationInicial1771033039468 implements MigrationInterface {
    name = 'MigrationInicial1771033039468'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE OR REPLACE FUNCTION immutable_array_to_string(arr text[], sep text)
            RETURNS text LANGUAGE sql IMMUTABLE STRICT
            AS $$ SELECT array_to_string(arr, sep); $$;
        `);
        await queryRunner.query(`CREATE TABLE "comp_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_01ddc49d2986d126a9a977cea83" UNIQUE ("code"), CONSTRAINT "PK_cce73128bce3fb326228655c865" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "weapon_properties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_3f57390ea75c3c6a68fdd592c35" UNIQUE ("slug"), CONSTRAINT "PK_c2881e2fe5f0815df142d3ec6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "weapon_mastery_properties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2b6da034f987666c24fb9028c95" UNIQUE ("slug"), CONSTRAINT "PK_11312bd0fbf82132c719fcf38b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proficiencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "proficiency_type" "public"."proficiency_type_enum" NOT NULL, "reference" jsonb NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0ce42b37736366495fd1cbde14e" UNIQUE ("slug"), CONSTRAINT "PK_3793ef9d0c2cd7fdc7ebd8d5209" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trait_proficiencies" ("trait_id" uuid NOT NULL, "proficiency_id" uuid NOT NULL, CONSTRAINT "PK_c3422f5126c0b0ba9595dc98128" PRIMARY KEY ("trait_id", "proficiency_id"))`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["neondb","public","traits","GENERATED_COLUMN","search_text","immutable_array_to_string(description, ' ')"]);
        await queryRunner.query(`CREATE TABLE "traits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text array NOT NULL, "search_text" text GENERATED ALWAYS AS (immutable_array_to_string(description, ' ')) STORED NOT NULL, "proficiency_choices" jsonb, "trait_specific" jsonb, "language_options" jsonb, "parent_id" uuid, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_1d7e240c2541e46c35100e827be" UNIQUE ("slug"), CONSTRAINT "PK_3956071aa0a8eb8210aa1c6a563" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "languages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "is_rare" boolean NOT NULL DEFAULT false, "note" text, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6a6bfd1fd58d167d3f84d16eefe" UNIQUE ("slug"), CONSTRAINT "PK_b517f827ca496b29f4d549c631d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "race_languages" ("race_id" uuid NOT NULL, "language_id" uuid NOT NULL, CONSTRAINT "PK_8b08a24c92e9b44befabf15e7f4" PRIMARY KEY ("race_id", "language_id"))`);
        await queryRunner.query(`CREATE TABLE "race_traits" ("race_id" uuid NOT NULL, "trait_id" uuid NOT NULL, CONSTRAINT "PK_25b61899d618fe858816100fe5a" PRIMARY KEY ("race_id", "trait_id"))`);
        await queryRunner.query(`CREATE TABLE "races" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "speed" integer NOT NULL, "ability_bonuses" jsonb NOT NULL, "age" text NOT NULL, "size" text NOT NULL, "size_description" text NOT NULL, "language_options" jsonb, "language_desc" text NOT NULL, "ability_bonus_options" jsonb, "alignment" text NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d3b5dafe9a7fd23f975261c8d05" UNIQUE ("slug"), CONSTRAINT "PK_ba7d19b382156bc33244426c597" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subrace_traits" ("subrace_id" uuid NOT NULL, "trait_id" uuid NOT NULL, CONSTRAINT "PK_69c02a63ee1ff6b6a35bef9164c" PRIMARY KEY ("subrace_id", "trait_id"))`);
        await queryRunner.query(`CREATE TABLE "subraces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "ability_bonuses" jsonb NOT NULL, "url" text, "race_id" uuid, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_aeab86471c741dd3d3a60b11faf" UNIQUE ("slug"), CONSTRAINT "PK_8c288b135f5563776ecd1428b1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_proficiencies" ("class_id" uuid NOT NULL, "proficiency_id" uuid NOT NULL, CONSTRAINT "PK_398db034c4be5f8b5e35a6a15f1" PRIMARY KEY ("class_id", "proficiency_id"))`);
        await queryRunner.query(`CREATE TABLE "skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "ability_score_id" uuid, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_55b7acbf80551e7fa2b5a33ed6c" UNIQUE ("slug"), CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ability_scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "full_name" character varying NOT NULL, "description" text NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c9a4533103173a1176893892edf" UNIQUE ("slug"), CONSTRAINT "PK_7d468d0e3157155a1116042f5cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_saving_throws" ("class_id" uuid NOT NULL, "ability_score_id" uuid NOT NULL, CONSTRAINT "PK_311a3e6aacda3c250edc2f4be6c" PRIMARY KEY ("class_id", "ability_score_id"))`);
        await queryRunner.query(`CREATE TABLE "equipment_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bc41dae678753a0dbc90d0785dc" UNIQUE ("slug"), CONSTRAINT "PK_323deb47d671c21e7666532c36c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equipment_category_items" ("equipment_id" uuid NOT NULL, "category_id" uuid NOT NULL, CONSTRAINT "PK_12a37c2b13165d73e2c130d4118" PRIMARY KEY ("equipment_id", "category_id"))`);
        await queryRunner.query(`CREATE TABLE "equipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "weight" numeric NOT NULL DEFAULT '0', "description" text, "image" text, "cost" jsonb NOT NULL, "damage" jsonb, "armor_class" jsonb, "properties" jsonb, "utilize" jsonb, "contents" jsonb, "craft" jsonb, "range" jsonb, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fccf3c0ddbe0bcd1e6a1a7390a3" UNIQUE ("slug"), CONSTRAINT "PK_250348d5d9ae4946bcd634f3e61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_starting_equipment" ("class_id" uuid NOT NULL, "equipment_id" uuid NOT NULL, CONSTRAINT "PK_037bdb88670e1c7e2fd78a62e37" PRIMARY KEY ("class_id", "equipment_id"))`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "hit_die" integer NOT NULL, "proficiency_choices" jsonb NOT NULL, "starting_equipment_options" jsonb, "class_levels_url" text, "multi_classing" jsonb NOT NULL, "spellcasting" jsonb, "spells_url" text, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e09658c598e10308a4e78a0130c" UNIQUE ("slug"), CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["neondb","public","subclasses","GENERATED_COLUMN","search_text","immutable_array_to_string(description, ' ')"]);
        await queryRunner.query(`CREATE TABLE "subclasses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "subclass_flavor" text NOT NULL, "description" text array NOT NULL, "search_text" text GENERATED ALWAYS AS (immutable_array_to_string(description, ' ')) STORED NOT NULL, "subclass_levels_url" text, "spells" jsonb, "class_id" uuid, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_dff149bb73ac9dd987439d79a35" UNIQUE ("slug"), CONSTRAINT "PK_5262eead58829915cf1472af99b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "magic_schools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d55f6722c312a49f09f9cea5aef" UNIQUE ("slug"), CONSTRAINT "PK_484307f405066372275c1c41d5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["neondb","public","spells","GENERATED_COLUMN","search_text","immutable_array_to_string(description || COALESCE(higher_level, ARRAY[]::text[]), ' ')"]);
        await queryRunner.query(`CREATE TABLE "spells" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text array NOT NULL, "higher_level" text array, "search_text" text GENERATED ALWAYS AS (immutable_array_to_string(description || COALESCE(higher_level, ARRAY[]::text[]), ' ')) STORED NOT NULL, "range" text NOT NULL, "components" jsonb NOT NULL, "material" text, "ritual" boolean NOT NULL, "duration" text NOT NULL, "concentration" boolean NOT NULL, "casting_time" text NOT NULL, "level" integer NOT NULL, "attack_type" "public"."attack_type_enum", "damage" jsonb, "url" text, "dc" jsonb, "heal_at_slot_level" jsonb, "area_of_effect" jsonb, "school_id" uuid, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_723397789d50703ec154028b10a" UNIQUE ("slug"), CONSTRAINT "PK_19d1052082c20f04349c0b5875c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "spell_subclasses" ("spell_id" uuid NOT NULL, "subclass_id" uuid NOT NULL, CONSTRAINT "PK_9034273c209ce955cd2470e4e40" PRIMARY KEY ("spell_id", "subclass_id"))`);
        await queryRunner.query(`CREATE TABLE "spell_classes" ("spell_id" uuid NOT NULL, "class_id" uuid NOT NULL, CONSTRAINT "PK_27fba37466f6fc038e0c4cb69a4" PRIMARY KEY ("spell_id", "class_id"))`);
        await queryRunner.query(`CREATE TABLE "rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "url" text, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_332b72b3fbb9b8a6209f9b53542" UNIQUE ("slug"), CONSTRAINT "PK_10fef696a7d61140361b1b23608" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rule_sections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0d70b7082968f371f63db19281f" UNIQUE ("slug"), CONSTRAINT "PK_1f58151f4ee00fb15a5269ed465" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rule_section_links" ("rule_id" uuid NOT NULL, "section_id" uuid NOT NULL, CONSTRAINT "PK_31717d40a1841cf6bc37dfbabdc" PRIMARY KEY ("rule_id", "section_id"))`);
        await queryRunner.query(`CREATE TABLE "monsters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "size" text NOT NULL, "type" text NOT NULL, "subtype" text, "alignment" text NOT NULL, "armor_class" jsonb NOT NULL, "hit_points" integer NOT NULL, "hit_dice" text NOT NULL, "hit_points_roll" text NOT NULL, "speed" jsonb NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "constitution" integer NOT NULL, "intelligence" integer NOT NULL, "wisdom" integer NOT NULL, "charisma" integer NOT NULL, "proficiencies" jsonb NOT NULL, "damage_vulnerabilities" jsonb NOT NULL, "damage_resistances" jsonb NOT NULL, "damage_immunities" jsonb NOT NULL, "condition_immunities" jsonb NOT NULL, "senses" jsonb NOT NULL, "languages" text NOT NULL, "proficiency_bonus" integer NOT NULL, "xp" integer NOT NULL, "special_abilities" jsonb, "actions" jsonb, "legendary_actions" jsonb, "reactions" jsonb, "forms" jsonb, "image" text, "description" text, "challenge_rating" double precision NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c1ab27054f4437dc7c1db936d90" UNIQUE ("slug"), CONSTRAINT "PK_54abad06b2131c35078519e9e19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "magic_item_variants" ("magic_item_id" uuid NOT NULL, "variant_magic_item_id" uuid NOT NULL, CONSTRAINT "PK_40b154949e6ef44847d5d3cb83f" PRIMARY KEY ("magic_item_id", "variant_magic_item_id"))`);
        await queryRunner.query(`CREATE TABLE "magic_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "rarity" jsonb NOT NULL, "is_variant" boolean NOT NULL DEFAULT false, "description" jsonb NOT NULL, "image" text, "url" text, "equipment_category_id" uuid, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe3e29830a44a32a95a9d3a9a84" UNIQUE ("slug"), CONSTRAINT "PK_3e3fd8e8f68ad7e94cc73b82068" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "features" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "level" integer NOT NULL, "description" jsonb NOT NULL, "prerequisites" jsonb NOT NULL, "reference" text, "feature_specific" jsonb, "class_id" uuid, "subclass_id" uuid, "parent_id" uuid, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_93f14fa9535b6ec752b32a48ba9" UNIQUE ("slug"), CONSTRAINT "PK_5c1e336df2f4a7051e5bf08a941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "level_features" ("level_id" uuid NOT NULL, "feature_id" uuid NOT NULL, CONSTRAINT "PK_e02da42b13890f5f74a238ffc2c" PRIMARY KEY ("level_id", "feature_id"))`);
        await queryRunner.query(`CREATE TABLE "levels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "level" integer NOT NULL, "url" text, "ability_score_bonuses" integer NOT NULL DEFAULT '0', "prof_bonus" integer, "spellcasting" jsonb, "class_specific" jsonb, "subclass_specific" jsonb, "class_id" uuid, "subclass_id" uuid, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_05f8dd8f715793c64d49e3f1901" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "feats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "feat_type" "public"."feat_type_enum" NOT NULL DEFAULT 'general', "repeatable" text, "prerequisites" jsonb, "prerequisite_options" jsonb, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b48a6597e93dc316dc7b0d6ab22" UNIQUE ("slug"), CONSTRAINT "PK_db97555d25017dc2af4b292d2ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "damage_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f330b3835e577063309d2d2a268" UNIQUE ("slug"), CONSTRAINT "PK_774eae19b9a0c0dcf52941c2b11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conditions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "url" text, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d928c50bd8eee2db83364a1105d" UNIQUE ("slug"), CONSTRAINT "PK_3938bdf2933c08ac7af7e0e15e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "background_proficiencies" ("background_id" uuid NOT NULL, "proficiency_id" uuid NOT NULL, CONSTRAINT "PK_ba7a4d4e1cf719427ee8a7bafa8" PRIMARY KEY ("background_id", "proficiency_id"))`);
        await queryRunner.query(`CREATE TABLE "backgrounds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "equipment_options" jsonb NOT NULL, "proficiency_choices" jsonb, "feat_id" uuid, "language_choices" jsonb, "feature" jsonb, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9b47acc1bdbff591c22a72362f3" UNIQUE ("slug"), CONSTRAINT "PK_a5457d0aae72f18efc3cdf6e6bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "alignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "abbreviation" character varying NOT NULL, "description" text NOT NULL, "source_id" uuid, "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a0bfa7e0ef62e70dc690edfaaee" UNIQUE ("slug"), CONSTRAINT "PK_791b0e88f94a57e804ffe4fda4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "weapon_properties" ADD CONSTRAINT "FK_37bc13adf92cce3cc5ec7dd6ca2" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weapon_mastery_properties" ADD CONSTRAINT "FK_b6327475625e8f2d48316d71119" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proficiencies" ADD CONSTRAINT "FK_d68ed68b6c3d5078f6bac20e9a2" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trait_proficiencies" ADD CONSTRAINT "FK_c5641f1da414aa5cf44f3c44eb9" FOREIGN KEY ("trait_id") REFERENCES "traits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trait_proficiencies" ADD CONSTRAINT "FK_cd036cacafa9601670f867e70f2" FOREIGN KEY ("proficiency_id") REFERENCES "proficiencies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "traits" ADD CONSTRAINT "FK_fcfc30dc7440a65bb1f7fea5e9f" FOREIGN KEY ("parent_id") REFERENCES "traits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "traits" ADD CONSTRAINT "FK_b54cd53848ac13ab3ac41154cc0" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "languages" ADD CONSTRAINT "FK_c9e96d33b0ee19267592b7c0018" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "race_languages" ADD CONSTRAINT "FK_2a9aaa693c657ee27f64bab94ce" FOREIGN KEY ("race_id") REFERENCES "races"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "race_languages" ADD CONSTRAINT "FK_2bf29f5f78d5df2c0dc7e6c41e0" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "race_traits" ADD CONSTRAINT "FK_265341b9cf68099db47d1acd3b8" FOREIGN KEY ("race_id") REFERENCES "races"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "race_traits" ADD CONSTRAINT "FK_6e16daeae8491ad459336f02d91" FOREIGN KEY ("trait_id") REFERENCES "traits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "races" ADD CONSTRAINT "FK_8864f52393885f426eb31153c66" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subrace_traits" ADD CONSTRAINT "FK_49834279a94245f0f08402751ae" FOREIGN KEY ("subrace_id") REFERENCES "subraces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subrace_traits" ADD CONSTRAINT "FK_21f1581d18922b5be26faf5ff46" FOREIGN KEY ("trait_id") REFERENCES "traits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subraces" ADD CONSTRAINT "FK_675d4e48384f80783ad3f2657f3" FOREIGN KEY ("race_id") REFERENCES "races"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subraces" ADD CONSTRAINT "FK_50491b3e6622754e8c99bc4f4fb" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_proficiencies" ADD CONSTRAINT "FK_8a7bc5bf28ab49e75ab001eb28e" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_proficiencies" ADD CONSTRAINT "FK_b490beee7c623f1898aea189084" FOREIGN KEY ("proficiency_id") REFERENCES "proficiencies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_79911a6486804268794c0585b8d" FOREIGN KEY ("ability_score_id") REFERENCES "ability_scores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_cb187cd3414c3c44da814c97256" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ability_scores" ADD CONSTRAINT "FK_5d52456e174fe6f64330a19ea86" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_saving_throws" ADD CONSTRAINT "FK_c1126813aac2c75cb18c66feffd" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_saving_throws" ADD CONSTRAINT "FK_46b6d82f52cfa0c8b99f58b071a" FOREIGN KEY ("ability_score_id") REFERENCES "ability_scores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment_categories" ADD CONSTRAINT "FK_6b8ef281c58c9323e3225a0ff9f" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment_category_items" ADD CONSTRAINT "FK_9c46de5cc52c641c47f7d7480d7" FOREIGN KEY ("equipment_id") REFERENCES "equipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment_category_items" ADD CONSTRAINT "FK_8436b38bd272cdbce512c4b8bd9" FOREIGN KEY ("category_id") REFERENCES "equipment_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipments" ADD CONSTRAINT "FK_128d1db16d260c7cabe8ab534df" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_starting_equipment" ADD CONSTRAINT "FK_624f47f5b07ca08e6f4295c7f1c" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_starting_equipment" ADD CONSTRAINT "FK_8b35e62e959c03e8ed4504a77c4" FOREIGN KEY ("equipment_id") REFERENCES "equipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_8898aa1e9cce99c76fc7cecdf3e" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subclasses" ADD CONSTRAINT "FK_0d219dfa912e25c4aac99ee61bc" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subclasses" ADD CONSTRAINT "FK_bf8909a170ba093811276c9f01c" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "magic_schools" ADD CONSTRAINT "FK_d33da0b6e9f5fca5c9aebb20197" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spells" ADD CONSTRAINT "FK_b96490c9035029b863000cf07fa" FOREIGN KEY ("school_id") REFERENCES "magic_schools"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spells" ADD CONSTRAINT "FK_2c05daec9419c960badd08fa9b8" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell_subclasses" ADD CONSTRAINT "FK_ac0bf96d12f7adf6c868fba85b1" FOREIGN KEY ("spell_id") REFERENCES "spells"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell_subclasses" ADD CONSTRAINT "FK_7f2b33d9f386baf4b8a79ac6560" FOREIGN KEY ("subclass_id") REFERENCES "subclasses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell_classes" ADD CONSTRAINT "FK_33afe3642c88a5b60c56fa245c5" FOREIGN KEY ("spell_id") REFERENCES "spells"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell_classes" ADD CONSTRAINT "FK_5112f8a085314573a84abdad374" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "FK_df5a277b8ace2709d37773bd05f" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_sections" ADD CONSTRAINT "FK_b301c9b67d3a818ab39d7a032b4" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_section_links" ADD CONSTRAINT "FK_00c634fec2d85747cf1e7c36d9b" FOREIGN KEY ("rule_id") REFERENCES "rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_section_links" ADD CONSTRAINT "FK_6622e0a3f730ee4d631af3006f8" FOREIGN KEY ("section_id") REFERENCES "rule_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monsters" ADD CONSTRAINT "FK_d98b39a8c40e8e383feb815f42e" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "magic_item_variants" ADD CONSTRAINT "FK_13c060dab7eda234c172394e00d" FOREIGN KEY ("magic_item_id") REFERENCES "magic_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "magic_item_variants" ADD CONSTRAINT "FK_8917f3506189f692032799cfa48" FOREIGN KEY ("variant_magic_item_id") REFERENCES "magic_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "magic_items" ADD CONSTRAINT "FK_50ed1d280765948af9fcc7e28b9" FOREIGN KEY ("equipment_category_id") REFERENCES "equipment_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "magic_items" ADD CONSTRAINT "FK_432e7614d2e45c9bfe7195665a8" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_070ab587d50489fb3848f44ffc4" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_fbcd6219e2fd355b9367e0e4a56" FOREIGN KEY ("subclass_id") REFERENCES "subclasses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_165a85471c3e66a06d5040d2705" FOREIGN KEY ("parent_id") REFERENCES "features"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_1d7220de52172e620f732a42a59" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "level_features" ADD CONSTRAINT "FK_a26464ba9738f50906ef12bedc6" FOREIGN KEY ("level_id") REFERENCES "levels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "level_features" ADD CONSTRAINT "FK_87311b33ef4ac4b99d7250fa8d9" FOREIGN KEY ("feature_id") REFERENCES "features"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "levels" ADD CONSTRAINT "FK_35ec8d01519fa09974d89b32aeb" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "levels" ADD CONSTRAINT "FK_2edb8698588517fb86eeb537157" FOREIGN KEY ("subclass_id") REFERENCES "subclasses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "levels" ADD CONSTRAINT "FK_de81ba0028f4a443baf18c5b39f" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feats" ADD CONSTRAINT "FK_1856de103312d9b5f36867570be" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "damage_types" ADD CONSTRAINT "FK_2850bb821f017ef0b1477d20f29" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conditions" ADD CONSTRAINT "FK_5c21727cfa80ae37f5f4d19558d" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "background_proficiencies" ADD CONSTRAINT "FK_7a87d8a2669eb398aaffb1ed1a5" FOREIGN KEY ("background_id") REFERENCES "backgrounds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "background_proficiencies" ADD CONSTRAINT "FK_5fe77c71716ed30b281c1071d86" FOREIGN KEY ("proficiency_id") REFERENCES "proficiencies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backgrounds" ADD CONSTRAINT "FK_6c6624e753c8d4b84ae4b91b4e9" FOREIGN KEY ("feat_id") REFERENCES "feats"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backgrounds" ADD CONSTRAINT "FK_7af39189792d9dd322a463754fc" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alignments" ADD CONSTRAINT "FK_8609dd925170b47d4dca5a44fab" FOREIGN KEY ("source_id") REFERENCES "comp_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "alignments" DROP CONSTRAINT "FK_8609dd925170b47d4dca5a44fab"`);
        await queryRunner.query(`ALTER TABLE "backgrounds" DROP CONSTRAINT "FK_7af39189792d9dd322a463754fc"`);
        await queryRunner.query(`ALTER TABLE "backgrounds" DROP CONSTRAINT "FK_6c6624e753c8d4b84ae4b91b4e9"`);
        await queryRunner.query(`ALTER TABLE "background_proficiencies" DROP CONSTRAINT "FK_5fe77c71716ed30b281c1071d86"`);
        await queryRunner.query(`ALTER TABLE "background_proficiencies" DROP CONSTRAINT "FK_7a87d8a2669eb398aaffb1ed1a5"`);
        await queryRunner.query(`ALTER TABLE "conditions" DROP CONSTRAINT "FK_5c21727cfa80ae37f5f4d19558d"`);
        await queryRunner.query(`ALTER TABLE "damage_types" DROP CONSTRAINT "FK_2850bb821f017ef0b1477d20f29"`);
        await queryRunner.query(`ALTER TABLE "feats" DROP CONSTRAINT "FK_1856de103312d9b5f36867570be"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP CONSTRAINT "FK_de81ba0028f4a443baf18c5b39f"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP CONSTRAINT "FK_2edb8698588517fb86eeb537157"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP CONSTRAINT "FK_35ec8d01519fa09974d89b32aeb"`);
        await queryRunner.query(`ALTER TABLE "level_features" DROP CONSTRAINT "FK_87311b33ef4ac4b99d7250fa8d9"`);
        await queryRunner.query(`ALTER TABLE "level_features" DROP CONSTRAINT "FK_a26464ba9738f50906ef12bedc6"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_1d7220de52172e620f732a42a59"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_165a85471c3e66a06d5040d2705"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_fbcd6219e2fd355b9367e0e4a56"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_070ab587d50489fb3848f44ffc4"`);
        await queryRunner.query(`ALTER TABLE "magic_items" DROP CONSTRAINT "FK_432e7614d2e45c9bfe7195665a8"`);
        await queryRunner.query(`ALTER TABLE "magic_items" DROP CONSTRAINT "FK_50ed1d280765948af9fcc7e28b9"`);
        await queryRunner.query(`ALTER TABLE "magic_item_variants" DROP CONSTRAINT "FK_8917f3506189f692032799cfa48"`);
        await queryRunner.query(`ALTER TABLE "magic_item_variants" DROP CONSTRAINT "FK_13c060dab7eda234c172394e00d"`);
        await queryRunner.query(`ALTER TABLE "monsters" DROP CONSTRAINT "FK_d98b39a8c40e8e383feb815f42e"`);
        await queryRunner.query(`ALTER TABLE "rule_section_links" DROP CONSTRAINT "FK_6622e0a3f730ee4d631af3006f8"`);
        await queryRunner.query(`ALTER TABLE "rule_section_links" DROP CONSTRAINT "FK_00c634fec2d85747cf1e7c36d9b"`);
        await queryRunner.query(`ALTER TABLE "rule_sections" DROP CONSTRAINT "FK_b301c9b67d3a818ab39d7a032b4"`);
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "FK_df5a277b8ace2709d37773bd05f"`);
        await queryRunner.query(`ALTER TABLE "spell_classes" DROP CONSTRAINT "FK_5112f8a085314573a84abdad374"`);
        await queryRunner.query(`ALTER TABLE "spell_classes" DROP CONSTRAINT "FK_33afe3642c88a5b60c56fa245c5"`);
        await queryRunner.query(`ALTER TABLE "spell_subclasses" DROP CONSTRAINT "FK_7f2b33d9f386baf4b8a79ac6560"`);
        await queryRunner.query(`ALTER TABLE "spell_subclasses" DROP CONSTRAINT "FK_ac0bf96d12f7adf6c868fba85b1"`);
        await queryRunner.query(`ALTER TABLE "spells" DROP CONSTRAINT "FK_2c05daec9419c960badd08fa9b8"`);
        await queryRunner.query(`ALTER TABLE "spells" DROP CONSTRAINT "FK_b96490c9035029b863000cf07fa"`);
        await queryRunner.query(`ALTER TABLE "magic_schools" DROP CONSTRAINT "FK_d33da0b6e9f5fca5c9aebb20197"`);
        await queryRunner.query(`ALTER TABLE "subclasses" DROP CONSTRAINT "FK_bf8909a170ba093811276c9f01c"`);
        await queryRunner.query(`ALTER TABLE "subclasses" DROP CONSTRAINT "FK_0d219dfa912e25c4aac99ee61bc"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_8898aa1e9cce99c76fc7cecdf3e"`);
        await queryRunner.query(`ALTER TABLE "class_starting_equipment" DROP CONSTRAINT "FK_8b35e62e959c03e8ed4504a77c4"`);
        await queryRunner.query(`ALTER TABLE "class_starting_equipment" DROP CONSTRAINT "FK_624f47f5b07ca08e6f4295c7f1c"`);
        await queryRunner.query(`ALTER TABLE "equipments" DROP CONSTRAINT "FK_128d1db16d260c7cabe8ab534df"`);
        await queryRunner.query(`ALTER TABLE "equipment_category_items" DROP CONSTRAINT "FK_8436b38bd272cdbce512c4b8bd9"`);
        await queryRunner.query(`ALTER TABLE "equipment_category_items" DROP CONSTRAINT "FK_9c46de5cc52c641c47f7d7480d7"`);
        await queryRunner.query(`ALTER TABLE "equipment_categories" DROP CONSTRAINT "FK_6b8ef281c58c9323e3225a0ff9f"`);
        await queryRunner.query(`ALTER TABLE "class_saving_throws" DROP CONSTRAINT "FK_46b6d82f52cfa0c8b99f58b071a"`);
        await queryRunner.query(`ALTER TABLE "class_saving_throws" DROP CONSTRAINT "FK_c1126813aac2c75cb18c66feffd"`);
        await queryRunner.query(`ALTER TABLE "ability_scores" DROP CONSTRAINT "FK_5d52456e174fe6f64330a19ea86"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_cb187cd3414c3c44da814c97256"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_79911a6486804268794c0585b8d"`);
        await queryRunner.query(`ALTER TABLE "class_proficiencies" DROP CONSTRAINT "FK_b490beee7c623f1898aea189084"`);
        await queryRunner.query(`ALTER TABLE "class_proficiencies" DROP CONSTRAINT "FK_8a7bc5bf28ab49e75ab001eb28e"`);
        await queryRunner.query(`ALTER TABLE "subraces" DROP CONSTRAINT "FK_50491b3e6622754e8c99bc4f4fb"`);
        await queryRunner.query(`ALTER TABLE "subraces" DROP CONSTRAINT "FK_675d4e48384f80783ad3f2657f3"`);
        await queryRunner.query(`ALTER TABLE "subrace_traits" DROP CONSTRAINT "FK_21f1581d18922b5be26faf5ff46"`);
        await queryRunner.query(`ALTER TABLE "subrace_traits" DROP CONSTRAINT "FK_49834279a94245f0f08402751ae"`);
        await queryRunner.query(`ALTER TABLE "races" DROP CONSTRAINT "FK_8864f52393885f426eb31153c66"`);
        await queryRunner.query(`ALTER TABLE "race_traits" DROP CONSTRAINT "FK_6e16daeae8491ad459336f02d91"`);
        await queryRunner.query(`ALTER TABLE "race_traits" DROP CONSTRAINT "FK_265341b9cf68099db47d1acd3b8"`);
        await queryRunner.query(`ALTER TABLE "race_languages" DROP CONSTRAINT "FK_2bf29f5f78d5df2c0dc7e6c41e0"`);
        await queryRunner.query(`ALTER TABLE "race_languages" DROP CONSTRAINT "FK_2a9aaa693c657ee27f64bab94ce"`);
        await queryRunner.query(`ALTER TABLE "languages" DROP CONSTRAINT "FK_c9e96d33b0ee19267592b7c0018"`);
        await queryRunner.query(`ALTER TABLE "traits" DROP CONSTRAINT "FK_b54cd53848ac13ab3ac41154cc0"`);
        await queryRunner.query(`ALTER TABLE "traits" DROP CONSTRAINT "FK_fcfc30dc7440a65bb1f7fea5e9f"`);
        await queryRunner.query(`ALTER TABLE "trait_proficiencies" DROP CONSTRAINT "FK_cd036cacafa9601670f867e70f2"`);
        await queryRunner.query(`ALTER TABLE "trait_proficiencies" DROP CONSTRAINT "FK_c5641f1da414aa5cf44f3c44eb9"`);
        await queryRunner.query(`ALTER TABLE "proficiencies" DROP CONSTRAINT "FK_d68ed68b6c3d5078f6bac20e9a2"`);
        await queryRunner.query(`ALTER TABLE "weapon_mastery_properties" DROP CONSTRAINT "FK_b6327475625e8f2d48316d71119"`);
        await queryRunner.query(`ALTER TABLE "weapon_properties" DROP CONSTRAINT "FK_37bc13adf92cce3cc5ec7dd6ca2"`);
        await queryRunner.query(`DROP TABLE "alignments"`);
        await queryRunner.query(`DROP TABLE "backgrounds"`);
        await queryRunner.query(`DROP TABLE "background_proficiencies"`);
        await queryRunner.query(`DROP TABLE "conditions"`);
        await queryRunner.query(`DROP TABLE "damage_types"`);
        await queryRunner.query(`DROP TABLE "feats"`);
        await queryRunner.query(`DROP TABLE "levels"`);
        await queryRunner.query(`DROP TABLE "level_features"`);
        await queryRunner.query(`DROP TABLE "features"`);
        await queryRunner.query(`DROP TABLE "magic_items"`);
        await queryRunner.query(`DROP TABLE "magic_item_variants"`);
        await queryRunner.query(`DROP TABLE "monsters"`);
        await queryRunner.query(`DROP TABLE "rule_section_links"`);
        await queryRunner.query(`DROP TABLE "rule_sections"`);
        await queryRunner.query(`DROP TABLE "rules"`);
        await queryRunner.query(`DROP TABLE "spell_classes"`);
        await queryRunner.query(`DROP TABLE "spell_subclasses"`);
        await queryRunner.query(`DROP TABLE "spells"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","search_text","neondb","public","spells"]);
        await queryRunner.query(`DROP TABLE "magic_schools"`);
        await queryRunner.query(`DROP TABLE "subclasses"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","search_text","neondb","public","subclasses"]);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TABLE "class_starting_equipment"`);
        await queryRunner.query(`DROP TABLE "equipments"`);
        await queryRunner.query(`DROP TABLE "equipment_category_items"`);
        await queryRunner.query(`DROP TABLE "equipment_categories"`);
        await queryRunner.query(`DROP TABLE "class_saving_throws"`);
        await queryRunner.query(`DROP TABLE "ability_scores"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP TABLE "class_proficiencies"`);
        await queryRunner.query(`DROP TABLE "subraces"`);
        await queryRunner.query(`DROP TABLE "subrace_traits"`);
        await queryRunner.query(`DROP TABLE "races"`);
        await queryRunner.query(`DROP TABLE "race_traits"`);
        await queryRunner.query(`DROP TABLE "race_languages"`);
        await queryRunner.query(`DROP TABLE "languages"`);
        await queryRunner.query(`DROP TABLE "traits"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","search_text","neondb","public","traits"]);
        await queryRunner.query(`DROP TABLE "trait_proficiencies"`);
        await queryRunner.query(`DROP TABLE "proficiencies"`);
        await queryRunner.query(`DROP TABLE "weapon_mastery_properties"`);
        await queryRunner.query(`DROP TABLE "weapon_properties"`);
        await queryRunner.query(`DROP TABLE "comp_sources"`);
        await queryRunner.query(`DROP FUNCTION IF EXISTS immutable_array_to_string(text[], text)`);
    }

}
