import type { EventCategory, EventEnvelope } from "./event-envelope.types";

export interface EventListener {
  readonly name: string;
  readonly categories: readonly EventCategory[];
  handle(envelope: EventEnvelope): Promise<void>;
}

const EVENT_TYPE_CATALOG: Record<EventCategory, ReadonlySet<string>> = {
  EncounterEvent: new Set([
    "damage_applied",
    "condition_added",
    "condition_removed",
    "participant_died",
    "spell_cast",
    "attack_resolved",
    "concentration_broken",
    "tile_effect_triggered",
    "encounter_started",
    "encounter_ended",
    "encounter_started_from_narrative",
    "random_encounter_started",
    "morale_check_failed",
    "dying_state_changed",
    "event_bus_overflow",
  ]),
  WorldEvent: new Set([
    "weather_changed",
    "chaos_factor_changed",
    "time_advanced",
    "period_changed",
    "poi_moved",
    "world_pulse_random_encounter_triggered",
    "location_revealed",
    "location_visited",
    "travel_started",
    "lighting_changed",
    "terrain_modified",
    "audience_map_changed",
    "event_bus_listener_failed",
    "quest_revealed",
    "quest_advanced",
    "quest_completed",
    "quest_failed",
    "main_quest_assigned",
    "phase_gate_pending",
    "phase_changed",
    "chaos_factor_evolved",
  ]),
  NarrativeEvent: new Set([
    "dialog_chosen",
    "lore_revealed",
    "quest_objective_completed",
    "persona_invoked",
    "narrative_decision_made",
    "voice_drift_detected",
    "tool_intent_rejected",
    "npc_moved",
    "npc_created",
    "revivify_eligibility_checked",
    "event_bus_listener_registered",
    "session_resumed",
    "scene_changed",
    "cold_open_generated",
    "phase_opened",
    "phase_completed",
    "xp_trigger_marked",
    "phase_outcome_derived",
    "bookend_ready",
    "bookend_failed",
    "previously_on_shown",
    "bookend_skipped",
    "movement_lock_changed",
    "dialogue_started",
    "dialogue_exited",
    "dialogue_focal_swapped",
    "meta_query_invoked",
    "clock_progressed",
    "clock_filled",
    "clock_resolved",

    "npc_witnessed_event",
    "guard_dispatched",
    "mission_progress_advanced",
    "director_pull_injected",
    "travel_action_applied",
    "dialogue_reveal",
    "compass_signal_emitted",
    "combat_intent_signal_emitted",
    "npc_posture_changed",
    "identity_tags_changed",
    "chronicle_tier_changed",
    "downtime_executed",
    "nl_trigger_evaluated",
    "story_completed",
    "story_failed",
    "ending_imminent",
  ]),
  SocialEvent: new Set([
    "companion_approval_changed",
    "companion_approval_threshold_crossed",
    "companion_recruited",
    "companion_dismissed",
    "companion_spoke",
    "companion_disagreement",
    "companion_relationship_phase_changed",
    "companion_romance_milestone",
    "disposition_changed",
    "reputation_shift",
    "companion_dialogue_unlocked",
    "bond_formed",
    "bond_broken",
    "item_lost",
    "item_awarded",
    "currency_changed",
    "loot_rolled",
    "healing_received",
    "hp_lost_narrative",
    "theft_from_pc",
    "theft_from_npc",

    "reputation_tag_added",
    "crime_committed",
  ]),
};

export function isEventTypeRegistered(
  category: EventCategory,
  eventType: string,
): boolean {
  const set = EVENT_TYPE_CATALOG[category];
  return set ? set.has(eventType) : false;
}